### ISSUE TITLE
Checkpoint 1

### ISSUE THREAD

**Issue by BryceAllard** [BryceAllard/ClimbLog#1]
Checkpoint 1 content ready for review

@pawaitemadisoncollege

**Comment by pawaitemadisoncollege** [comment]
Hi @BryceAllard!

Thanks for sharing your indie project checkpoint 1! It sounds like you chose a project that is meaningful to you and I hope that helps you stay excited about this work throughout the semester.  I personally love the idea as it includes some of my favorite things: outdoor adventure and maps.

Following are my observations and suggestions:

**Problem statement**

Does a good job laying out the problem and explaining how your application solves it. 

- [ ] Technology list has a large number of items under "tech I'd like to explore" - might be good to narrow this to one... or two... that really interest you. You do not have to do it all in the next 11 weeks :) 

**User stories**

Your MVP user stories feel like they are right-sized for the semester while meeting the requirements of Ent Java - for example, full CRUD and using a service (weather). That said, sometimes I am too optimistic/ambitious, so let's both keep an eye on how things progress and what, if anything needs to be delayed to V2. 

- [ ] Formatting doesn't look great in GitHub. 
- [ ] Would it make sense for a user to be able to edit or delete the climbs they have entered. You don't _have_ to have an admin role (could be stretch goal). Totally your choice here and what makes sense to you for your application. 

**Project plan**

- [ ] Formatting is really hard to read in GitHub. Can you fix it up and then I'll review in more detail.

**Screen design**

- [ ] I wonder if the search results would be more useful if the results table included more detail than the climb name? If more columns were shown, the jquery datatable could provide additional sorting/filtering. (see week 2 solution video for an example)

**Reflection statements/Time Log**

Great work consistently tracking!

I'm really looking forward to seeing progress on this one!

**Comment by BryceAllard** [comment]
Feedback implemented. Will look at expanding search results when I get to that portion of the project.

**Comment by pawaitemadisoncollege** [comment]
Nice job with the improvements - looks much better @BryceAllard!

Remember to check off completed tasks on your plan when you get a chance. I think you have more done than what's shown.
